prj_name/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('core.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += staticfiles_urlpatterns()

prj_name/core/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=255)

    def __unicode__(self):
        return '%s' % self.title


class Ingredient(models.Model):
    title = models.CharField(max_length=255)

    def __unicode__(self):
        return '%s' % self.title


class IngredientCount(models.Model):
    '''Additional model to store amount of
    selected ingredient

    '''

    ingredient = models.ForeignKey(Ingredient,
                        related_name='ingredient_counts')
    cocktail = models.ForeignKey('core.Cocktail',
                        related_name='cocktail_counts')
    count = models.CharField(null=True, blank=True, max_length=255)

    def __unicode__(self):
        return '%s:%s %s' % (self.cocktail, self.ingredient, self.count)


class Cocktail(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(Category)
    ingredients = models.ManyToManyField(Ingredient, through=IngredientCount)

    def __unicode__(self):
        return '%s' % self.title

prj_name/templates/base.html
{% load i18n %}
<html>
<head>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>

</head>

<body>

{% block navbar %}
<a href='/'>{% trans 'Main' %}</a>
<a href='{% url categories %}'>{% trans 'Categories' %}</a>
<a href='{% url ingredients %}'>{% trans 'Ingredients' %}</a>
<a href='{% url cocktails %}'>{% trans 'Cocktails' %}</a>
<a href='{% url get_widget_code %}'>{% trans 'Get widget code' %}</a>
{% endblock %}

{% block content %}

{% endblock %}

</body>
</html>

prj_name/templates/categories.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<h1>{{ msg }}</h1>


<a href="{% url category_add %}"> {% trans 'Add category' %}</a>

<ul>
{% for category in categories %}
    <li>
        <a href="{% url category_show id=category.id %}"> {{ category }}</a>
        <a href="{% url category_show_remove to_remove=1 id=category.id %}"> {% trans 'Remove' %}</a>
        <a href="{% url category_edit id=category.id %}"> {% trans 'Edit' %}</a>
    </li>
{% endfor %}
</ul>

{% endblock %}

prj_name/templates/category.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<h1>{{ msg }}</h1>


{% if form %}
    <form method="POST" action='.'>
    {{ form }}
    {% csrf_token %}
    <input type="submit">
    </form>
{% endif %}

{% if to_remove %}
    <p>
    {% blocktrans %}
    Are you really want to remove this category
    with all cocktails listed bellow?
    {% endblocktrans %}
    <br/>
    <a href="{% url category_remove id=category.id %}"> {% trans 'Remove' %}</a>
    <a href="{% url categories %}"> {% trans 'Return to categories list' %}</a>
    </p>
    <br/>

{% endif %}


{% if category %}
    {% trans 'Category' %}: {{ category }}
{% endif %}




{% if category.cocktail_set.all %}
    <h3>{% trans 'List of cocktails of this category' %}</h3>
    <ul>
    {% for cocktail in category.cocktail_set.all %}
        <li>{{ cocktail }}</li>
    {% endfor %}
    </ul>
{% else %}
    <h3>{% trans 'There are no cocktails in this category' %}</h3>
{% endif %}

{% endblock %}

prj_name/templates/cocktail.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}


<script src="http://django-dynamic-formset.googlecode.com/svn/trunk/src/jquery.formset.min.js"></script>


    <script type="text/javascript">
    <!--
           $(function() {
               $('#cocktail_form .ingredients_formset:last').formset({});
           })
    //-->
    </script>

<h1>{{ msg }}</h1>
{% if form %}
    <form method="POST" action='.' id="cocktail_form">
    {{ ingredients_formset.management_form }}
    {{ form.management_form }}

    <table id="">
    {{ form.as_table }}
    </table>

    {% for ingredients_form in ingredients_formset %}
        <table class="ingredients_formset">
            {{ ingredients_form.as_table }}
        </table>
    {% endfor %}

    <br/>
    <br/>
    {% csrf_token %}
    <input type="submit">
    </form>
{% endif %}


{% if cocktail and not form %}
    <b>{{ cocktail.title }}</b>
    <br/>
    {{ cocktail.description }}
    <br/>
    <br/>
    {% trans 'ingredients:' %}
    {% for ingredient_count in cocktail.cocktail_counts.all %}
        {{ ingredient_count.count }} {{ ingredient_count.ingredient.title }}{% if not forloop.last %}, {% endif %}
    {% endfor %}

{% endif %}




{% endblock %}

prj_name/templates/cocktails.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<h1>{{ msg }}</h1>


<a href="{% url cocktail_add %}"> {% trans 'Add cocktail' %}</a>

<ul>
{% for cocktail in cocktails %}
    <li>
        <a href="{% url cocktail_show id=cocktail.id %}">{{ cocktail }}</a> 
        <a href="{% url cocktail_remove id=cocktail.id %}"> {% trans 'Remove' %}</a>
        <a href="{% url cocktail_edit id=cocktail.id %}"> {% trans 'Edit' %}</a>
    </li>
{% endfor %}
</ul>

{% endblock %}

prj_name/templates/get_widget_code.html
{% extends 'base.html' %}

{% block content %}

<br/>
<br/>
<br/>
<script type="text/javascript"></script>
<textarea rows=30 cols=80>
<div id="cocktail_widget"></div>
<script type="text/javascript">
    cocktail_server = "http://{{ current_domain }}";
  (function() {
    var cs = document.createElement('script');
    cs.setAttribute('async', 'true');
    cs.type = 'text/javascript';
    cs.src = "http://{{ current_domain }}{{ STATIC_URL }}js/widget.js";
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(cs, s);

  })();

</script>
</textarea>
{% endblock %}

prj_name/templates/index.html
{% extends 'base.html' %}

{% block content %}

<br/>
<br/>
<br/>

<div id="cocktail_widget"></div>
<script type="text/javascript">
    cocktail_server = "http://127.0.0.1:8816";
  (function() {
    var cs = document.createElement('script');
    cs.setAttribute('async', 'true');
    cs.type = 'text/javascript';
    cs.src = "http://127.0.0.1:8816/static/js/widget.js";
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(cs, s);

  })();

</script>


{% endblock %}

prj_name/templates/ingredient.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<h1>{{ msg }}</h1>
{% if form %}
    <form method="POST" action='.'>
    {{ form }}
    {% csrf_token %}
    <input type="submit">
    </form>
{% endif %}

{% if to_remove %}
    <p>
    {% blocktrans %}
    Are you really want to remove this ingredient
    with all cocktails listed bellow?
    {% endblocktrans %}
    <br/>
    <a href="{% url ingredient_remove id=ingredient.id %}"> {% trans 'Remove' %}</a>
    <a href="{% url ingredients %}"> {% trans 'Return to ingredients list' %}</a>
    </p>
    <br/>

{% endif %}


{% if ingredient %}
    {% trans 'Ingredient' %}: {{ ingredient }}
{% endif %}
<br/>
{% if ingredient.cocktail_set.all %}
<h3>{% trans 'List of cocktails' %}</h3>
<ul>
{% for cocktail in ingredient.cocktail_set.all %}
    <li>{{ cocktail }}</li>
{% endfor %}
</ul>
{% else %}
    {% trans 'There are no cocktails found for this ingredient' %}
{% endif %}

{% endblock %}

prj_name/templates/ingredients.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<h1>{{ msg }}</h1>


<a href="{% url ingredient_add %}"> {% trans 'Add ingredient' %}</a>

<ul>
{% for ingredient in ingredients %}
    <li>
        <a href="{% url ingredient_show id=ingredient.id %}">{{ ingredient }}</a>
        <a href="{% url ingredient_show_remove to_remove=1 id=ingredient.id %}"> {% trans 'Remove' %}</a>
        <a href="{% url ingredient_edit id=ingredient.id %}"> {% trans 'Edit' %}</a>
    </li>
{% endfor %}
</ul>

{% endblock %}

prj_name/templates/widget.html
{% load i18n %}
<style>
    .cocktail_box{
        width: 300px;
        height:300px;
        background:wheat;
    }
</style>

<div class="cocktail_box">
{% if data %}
    <b>{{ data.title }}</b>
    <br>
    {{ data.description }}
    <br/>
    <br/>
    {% trans 'ingredients:' %}
    {% for ingredient in data.ingredients %}
        {{ ingredient }}{% if not forloop.last %}, {% endif %}
    {% endfor %}
    <br/>
    <br/>
    {% trans "source:" %} {{ data.source }}
{% else %}
    {{ error }}
{% endif %}
<input type="button" id="show_more_cocktails" value="Next random coktail, please!"/>
</div>